# Generated by Django 4.2.5 on 2023-09-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', models.CharField(max_length=200)),
                ('number_group', models.IntegerField()),
                ('count_students', models.IntegerField()),
                ('subject', models.CharField(max_length=200)),
            ],
        ),
    ]
